[project]
name = 'musics'
version = '0.1'
requires-python = '>=3.10'
dependencies = [
  'rich',
  'fastapi[standard]'
]

[project.optional-dependencies]
test = [
  'pytest',
  'pytest-cov',
  'ruff'
]

[tool.pytest.ini_options]
addopts = "--cov=musics --cov=tests --cov-report=term-missing"
